name: K6 Performance CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # Tambahkan ini agar semua container di job ini berbagi network host
    container:
      image: node:20 # Menggunakan image node agar kompatibel dengan app kamu
      options: --network host 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run API
        run: |
          npm install
          node app.js & # Jalankan di background
          sleep 10 # Tunggu API siap

      - name: Run k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: load-test.js